# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to=b'')),
                ('filepath', models.FilePathField()),
                ('title', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('year', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DisLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FHLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMode', models.CharField(choices=[('B', 'Builder'), ('R', 'Reader')], default='R', max_length=1)),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='audioBook',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FHLBuilder.Common')),
                ('author', models.CharField(max_length=63)),
            ],
            bases=('FHLBuilder.common',),
        ),
        migrations.CreateModel(
            name='eBook',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FHLBuilder.Common')),
                ('author', models.CharField(max_length=63)),
            ],
            bases=('FHLBuilder.common',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FHLBuilder.Common')),
                ('director', models.CharField(max_length=63)),
                ('actors', models.ManyToManyField(to='FHLBuilder.Tag')),
            ],
            bases=('FHLBuilder.common',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FHLBuilder.Common')),
                ('album', models.CharField(max_length=63)),
                ('artist', models.CharField(max_length=63)),
                ('track', models.IntegerField()),
            ],
            bases=('FHLBuilder.common',),
        ),
        migrations.AddField(
            model_name='loves',
            name='loved',
            field=models.ManyToManyField(to='FHLBuilder.Common'),
        ),
        migrations.AddField(
            model_name='loves',
            name='lovedBy',
            field=models.ManyToManyField(to='FHLBuilder.FHLUser'),
        ),
        migrations.AddField(
            model_name='likes',
            name='liked',
            field=models.ManyToManyField(to='FHLBuilder.Common'),
        ),
        migrations.AddField(
            model_name='likes',
            name='likedBy',
            field=models.ManyToManyField(to='FHLBuilder.FHLUser'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='disLiked',
            field=models.ManyToManyField(to='FHLBuilder.Common'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='disLikedBy',
            field=models.ManyToManyField(to='FHLBuilder.FHLUser'),
        ),
        migrations.AddField(
            model_name='common',
            name='tag',
            field=models.ManyToManyField(to='FHLBuilder.Tag'),
        ),
    ]
