# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHLBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FHLBuilder.Common')),
            ],
            bases=('FHLBuilder.common',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FHLBuilder.Common')),
                ('author', models.CharField(max_length=63)),
                ('chapterNumber', models.IntegerField()),
            ],
            bases=('FHLBuilder.common',),
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='common_ptr',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='common',
            name='fileKind',
            field=models.CharField(choices=[('A', 'Audio'), ('V', 'Video')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='eBook',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FHLBuilder.Song'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FHLBuilder.Chapter'),
        ),
    ]
