# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHLBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfile',
            name='fileKind',
            field=models.CharField(choices=[('SG', 'song'), ('PT', 'picture'), ('MV', 'Movie'), ('M3', '3D Movie'), ('MC', 'Movie-Cartoon'), ('MM', 'Mini-movie'), ('CC', 'Concert'), ('DD', 'Documentary'), ('TV', 'TV-show'), ('TC', 'TV-Cartoon'), ('TS', 'TV-Sitcom'), ('MS', 'Mini-series'), ('BR', 'BF-random'), ('AB', 'audio-book'), ('EB', 'e-book'), ('GG', 'Game'), ('UN', 'unknown')], default='UN', max_length=10),
        ),
    ]
