# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHLBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='song_musicians', to='FHLBuilder.Song'),
        ),
    ]
