# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FHLBuilder', '0002_auto_20170504_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfile',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
