# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHLBuilder', '0003_auto_20170320_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songsHead', models.CharField(max_length=100)),
                ('moviesHead', models.CharField(max_length=100)),
                ('booksHead', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='common',
            name='filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='common',
            name='filepath',
            field=models.CharField(max_length=100),
        ),
    ]
