# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHLBuilder', '0004_auto_20170323_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='common',
            name='filepath',
        ),
        migrations.AddField(
            model_name='collection',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FHLBuilder.Common'),
        ),
    ]
